import dayjs from 'dayjs';

const thisMonth = dayjs().format('MM');
const prevMonth = dayjs().subtract(1, 'month').format('MM');
const nextMonth = dayjs().add(1, 'month').format('MM');

export const schedules: ISchedule[] = [
  {
    id: '1',
    title: 'Mastering Digital Marketing',
    startDate: `2025-${thisMonth}-07`,
    endDate: `2025-${thisMonth}-08`,
    backgroundColor: '#456EF4',
    textColor: '#ffffff',
  },
  {
    id: '2',
    title: 'Introduction to Data Science',
    startDate: `2025-${thisMonth}-01`,
    endDate: `2025-${thisMonth}-08`,
    backgroundColor: '#456EF4',
    textColor: '#ffffff',
  },
  {
    id: '3',
    title: 'Fundamentals of Marketing in the Digital Age',
    startDate: `2025-${thisMonth}-08`,
    endDate: `2025-${thisMonth}-12`,
    backgroundColor: '#0EB942',
    textColor: '#ffffff',
  },
  {
    id: '4',
    title: 'Creative Writing for Beginner',
    startDate: `2025-${thisMonth}-09`,
    endDate: `2025-${thisMonth}-09`,
    backgroundColor: '#0EB942',
    textColor: '#ffffff',
  },
  {
    id: '5',
    title: 'Fundamentals of Webs',
    startDate: `2025-${thisMonth}-08`,
    endDate: `2025-${thisMonth}-08`,
    backgroundColor: '#0EB942',
    textColor: '#ffffff',
  },
  {
    id: '6',
    title: 'Fundamentals of Mobile',
    startDate: `2025-${thisMonth}-08`,
    endDate: `2025-${thisMonth}-09`,
    backgroundColor: '#0EB942',
    textColor: '#ffffff',
  },
  {
    id: '7',
    title: 'Fundamentals of Desktop',
    startDate: `2025-${thisMonth}-10`,
    endDate: `2025-${thisMonth}-12`,
    backgroundColor: '#b90e41',
    textColor: '#ffffff',
  },
  {
    id: '8',
    title: 'How to create an event?',
    startDate: `2025-${thisMonth}-06`,
    endDate: `2025-${thisMonth}-07`,
    backgroundColor: '#b90e41',
    textColor: '#ffffff',
  },
  {
    id: '9',
    title: 'How to create website?',
    startDate: `2025-${thisMonth}-09`,
    endDate: `2025-${thisMonth}-12`,
    backgroundColor: '#b90e41',
    textColor: '#ffffff',
  },
  {
    id: '10',
    title: 'How to create mobile app?',
    startDate: `2025-${thisMonth}-11`,
    endDate: `2025-${thisMonth}-16`,
    backgroundColor: '#b90e41',
    textColor: '#ffffff',
  },
  {
    id: '11',
    title: 'UI/UX Design Basics',
    startDate: `2025-${prevMonth}-23`,
    endDate: `2025-${prevMonth}-28`,
    backgroundColor: '#b9b60e',
    textColor: '#ffffff',
  },
  {
    id: '12',
    title: 'Python for Beginners',
    startDate: `2025-${prevMonth}-15`,
    endDate: `2025-${prevMonth}-23`,
    backgroundColor: '#5e0eb9',
    textColor: '#ffffff',
  },
  {
    id: '13',
    title: 'Cloud Computing Essentials',
    startDate: `2025-${nextMonth}-01`,
    endDate: `2025-${nextMonth}-04`,
    backgroundColor: '#b90e5e',
    textColor: '#ffffff',
  },
  {
    id: '14',
    title: 'Cybersecurity Fundamentals',
    startDate: `2025-${nextMonth}-05`,
    endDate: `2025-${nextMonth}-10`,
    backgroundColor: '#69b90e',
    textColor: '#ffffff',
  },
];
